#!/bin/bash

cat users.txt | while read username groupname ; do
  adduser $username
  usermod -a -G $groupname $username
  mkdir /home/$username/.ssh
  chown $username:$username /home/$username/.ssh
  cat keys/$username.pub >>/home/$username/.ssh/authorized_keys
  chown $username:$username /home/$username/.ssh/authorized_keys 
  chmod 600 /home/$username/.ssh/authorized_keys
done
