#!/bin/bash
yum -y install iptables-services
systemctl enable iptables
service iptables start
sed -i 's/crashkernel=/rootflags=grpquota crashkernel=/' /etc/default/grub
grub2-mkconfig -o /boot/grub2/grub.cfg
echo "Don't forget to reboot in order to enable quota"
